ALTER TABLE viajes_bitacora
  ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(100) NULL;

UPDATE viajes_bitacora
SET deleted = FALSE
WHERE deleted IS NULL;
